package cn.learnmybatis;


import cn.learnmybatis.chapter4.mapper.BaseMapperWorkTest;
import cn.learnmybatis.chapter4.model.SysUser;
import cn.learnmybatis.work.domain.PadataTwo;
import cn.learnmybatis.work.mapper.PadataTwoMapper;
import org.apache.ibatis.session.SqlSession;
import org.testng.annotations.Test;

/**
 * Created by Administrator on 2018/10/31 0031.
 */
public class WorkTest extends BaseMapperWorkTest{

    @Test
    public void importWorkTest() {
        String[] arrStr = getArryString();
        SqlSession sqlSession = getSqlSession();
        PadataTwoMapper padataTwoMapper = sqlSession.getMapper(PadataTwoMapper.class);

        for (int i = 0; i < 5500; i++) {
            PadataTwo padataTwo = padataTwoMapper.selectPadataTwoById(i);
            if (padataTwo == null) {
                continue;
            } else {
                padataTwo.setGongsidizhi(arrStr[i % arrStr.length]);
                padataTwoMapper.updatePadataTwo(padataTwo);
            }
        }

        sqlSession.commit();

        sqlSession.close();
    }

    @Test
    public void importWorkZhiWeiMingTest() {
        String[] arrStr = getArryZhiWeiStr();
        System.out.println(arrStr.length);

        SqlSession sqlSession = getSqlSession();
        PadataTwoMapper padataTwoMapper = sqlSession.getMapper(PadataTwoMapper.class);

        for (int i = 38; i < 5500; i++) {
            PadataTwo padataTwo = padataTwoMapper.selectPadataTwoById(i);
            if (padataTwo == null) {
                continue;
            } else {
                padataTwo.setZhiweiming(arrStr[i % arrStr.length]);
                padataTwoMapper.updatePadataTwo(padataTwo);
            }
        }


        sqlSession.commit();

        sqlSession.close();
    }

    @Test
    public void importWorkGongSiMingTest() {
        String[] arrStr = getArryGongSiMing();
        System.out.println(arrStr.length);

        SqlSession sqlSession = getSqlSession();
        PadataTwoMapper padataTwoMapper = sqlSession.getMapper(PadataTwoMapper.class);

        for (int i = 0; i < 5500; i++) {
            PadataTwo padataTwo = padataTwoMapper.selectPadataTwoById(i);
            if (padataTwo == null) {
                continue;
            } else {
                padataTwo.setGongsiming(arrStr[i % arrStr.length]);
                padataTwoMapper.updatePadataTwo(padataTwo);
            }
        }


        sqlSession.commit();

        sqlSession.close();
    }

    private String[] getArryGongSiMing(){

        String str="广东原动力信息科技有限责任公司fenge广州大为文化股份有限公司fengeGworld（平潭）互联网科技有限公司fengeIBMChinafengeUC优视（UC浏览器）fengeURfenge上海中信信息发展股份有限公司-数字档案室事业部fenge上海光奈网络科技有限公司广州分公司fenge上海华钦信息科技股份有限公司fenge上海哇麦信息技术有限公司广州分公司fenge上海宝供公路快运有限公司fenge上海易娱网络科技有限公司广州分公司fenge上海易立德信息技术股份有限公司fenge上海泛微网络科技股份有限公司fenge上海源慧信息科技股份有限公司fenge上海瑞玩网络科技有限公司fenge上海百胜软件股份有限公司fenge上海盛赫信息科技有限公司广州分公司fenge上海睿民互联网科技有限公司fenge上海翡翠东方网络信息技术有限公司fenge上海融铜信息科技有限公司fenge上海诺祺科技有限公司fenge上海逸豆数码科技有限公司fenge上海非码网络科技有限公司fenge上海鲸团科技有限公司fenge中国光大银行股份有限公司广州分行fenge中国电信集团公司总部fenge中国通信服务股份有限公司fenge中大黄埔国际教育fenge中山市和通游戏技术开发有限公司fenge中山市年轮电子科技有限公司fenge中数通信息有限公司fenge中水三立数据技术股份有限公司（原合肥三立自动化工程有限公司）fenge中经汇通电子商务有限公司fenge中软国际科技服务有限公司fenge亚信科技（中国）有限公司fenge佛山市顺德区智谷数码科技有限公司fenge侨银环保科技股份有限公司fenge信必优(深圳)信息技术有限公司fenge信雅达系统工程股份有限公司fenge信雅达（杭州）计算机服务有限公司fenge全城握手（广州）科技有限公司fenge凯豪信息科技股份有限公司fenge分之道(广州)教育网络科技有限公司fenge前海港亨信息科技（深圳）有限公司广州分公司fenge北京三五通联科技发展有限公司fenge北京公瑾科技有限公司广州分公司（慧算账）fenge北京北大软件工程股份有限公司fenge北京华亘安邦科技有限公司fenge北京南北天地科技股份有限公司广州分公司fenge北京大诚若谷信息技术有限公司fenge北京宽广智通信息技术有限公司fenge北京开科唯识技术有限公司fenge北京海联捷讯科技股份有限公司广州分公司fenge北京清软创新科技股份有限公司fenge北京石基大商信息技术有限公司fenge北京科云互联科技有限公司fenge北京网尚数字电影院线有限公司fenge北京路遥科技有限公司fenge北京金之盾信息技术有限公司fenge医服天下（深圳）科技有限公司fenge卓志供应链集团fenge卓望信息技术（北京）有限公司fenge南京华苏科技有限公司fenge南京唯实科技有限公司fenge南京泽谷软件有限公司fenge南京烽火星空通信发展有限公司fenge博创智能装备股份有限公司fenge博纳德集团fenge印孚瑟斯技术（中国）有限公司fenge厦门港云信息技术有限公司fenge古莘信息技术（广州）有限公司fenge可爱可亲（广州）高新科技有限公司fenge合肥英泽信息科技有限公司fenge同方知网（北京）技术有限公司广东分公司fenge周生生（中国）商业有限公司fenge和元达信息科技有限公司fenge城云科技（中国）有限公司fenge大连博创人力资源开发有限公司fenge大连赛伯信息技术有限公司fenge天地融科技股份有限公司fenge天翼爱音乐文化科技有限公司fenge天翼电子商务有限公司fenge太平洋网络fenge奇翼（上海）信息技术有限公司fenge威创集团股份有限公司fenge学府（国际）咨询机构fenge宝盛集团fenge富海阳光（北京）技术发展有限公司fenge小蝌蚪互联网科技（广州）有限公司fenge屈臣氏个人用品商店有限公司fenge山东威林科电子工程有限公司fenge常州格力博有限公司fenge广东三赢科技有限公司fenge广东中车检汽车服务咨询有限公司fenge广东中辰华锐企业管理有限公司fenge广东乐迹网络科技有限公司fenge广东云智居科技有限公司fenge广东亿迅科技有限公司fenge广东代言十科技有限公司fenge广东信基蜂巢科技有限责任公司fenge广东修炼科技股份有限公司fenge广东元韬企业管理咨询有限公司fenge广东全彩科技有限公司fenge广东六维生活信息科技有限公司fenge广东兰贝斯科技有限公司fenge广东分利宝金服科技有限公司fenge广东医链科技有限公司fenge广东十一维空间旅行社股份有限公司fenge广东华仝九方科技有限公司fenge广东华风海洋信息系统服务有限公司fenge广东南方信息安全产业基地有限公司fenge广东南油对外服务有限公司fenge广东原动力信息科技有限责任公司fenge广东和讯创智智能科技股份有限公司fenge广东国图勘测地理信息有限公司fenge广东坤智科技有限公司fenge广东大唐网游信息科技有限公司fenge广东天基网控环境科技有限公司fenge广东奥园奥买家电子商务有限公司fenge广东宜通世纪科技股份有限公司fenge广东广凌信息科技股份有限公司fenge广东广新家具有限公司fenge广东弘贝融科信息科技有限公司fenge广东微模式软件股份有限公司fenge广东德生科技股份有限公司fenge广东思埠集团有限公司fenge广东拜登网络技术有限公司fenge广东斯品家居科技有限公司fenge广东新华南方软件外包有限公司fenge广东新起点体育有限公司fenge广东方纬科技有限公司fenge广东旺大集团股份有限公司fenge广东明世教育集团有限公司fenge广东易教优培教育科技有限公司fenge广东星城科技有限公司fenge广东星舆科技有限公司fenge广东昱辉通信技术有限公司fenge广东曼拓信息科技有限公司fenge广东未来教育技术有限公司fenge广东机场白云信息科技有限公司fenge广东汉佳信息技术有限公司fenge广东海聊科技有限公司fenge广东涌浪网络技术有限公司fenge广东燧人消防安全评估技术研究有限公司fenge广东用心网络科技有限公司fenge广东申菱环境系统股份有限公司fenge广东百望九赋电子有限公司fenge广东盟讯科技有限公司fenge广东省脐带血造血干细胞库fenge广东紫光云平台数据服务有限公司fenge广东网域科技有限公司fenge广东网金控股股份有限公司fenge广东美捷威通生物科技有限公司fenge广东美电贝尔科技集团股份有限公司fenge广东美胸汇网络科技有限公司fenge广东联汛教育科技有限公司fenge广东联航智能科技有限公司fenge广东誉丰教育科技有限公司fenge广东诚泰交通科技发展有限公司fenge广东赛百威信息科技有限公司fenge广东赤朝科技有限公司fenge广东路卡服装集团有限公司fenge广东轩辕网络科技股份有限公司fenge广东道一信息技术股份有限公司fenge广东采联采购招标有限公司fenge广东金兴发检测评价咨询有限公司fenge广东鑫零售投资有限公司fenge广东钰昊科技有限公司fenge广东长隆集团有限公司fenge广东韵为大数据技术咨询有限公司fenge广东黾车新能源汽车产业有限公司fenge广东齐创科技投资集团有限公司fenge广州一一网络技术有限公司fenge广州一匡互联网科技有限公司fenge广州一智通供应链管理有限公司fenge广州丁香软件有限公司fenge广州万迅电脑软件有限公司fenge广州中广计算机科技有限公司fenge广州中海达卫星导航技术股份有限公司fenge广州中科云图智能科技有限公司fenge广州中科旗信软件科技有限公司fenge广州中职信会计师事务所有限公司fenge广州中胜物联网络科技有限公司fenge广州中铁信息工程有限公司fenge广州丽晶软件科技股份有限公司fenge广州久零区块链技术有限公司fenge广州乐速通信系统开发有限公司fenge广州九州塔苏斯展览有限公司fenge广州云实信息科技有限公司fenge广州云徙科技有限公司fenge广州云智通信息科技有限公司fenge广州云趣信息科技有限公司fenge广州云软数据科技有限公司fenge广州互信电子科技有限公司fenge广州亚美信息科技有限公司fenge广州亦云信息技术股份有限公司fenge广州人资选互联网科技有限公司fenge广州仪速安电子科技有限公司fenge广州企成信息科技有限公司fenge广州众攀网络科技有限公司fenge广州伯俊软件科技有限公司fenge广州佰仲企业管理顾问有限公司fenge广州佰希区块链科技有限公司fenge广州依琳信息科技有限公司fenge广州健民医药连锁有限公司fenge广州元曜软件有限公司fenge广州光娱信息科技有限公司fenge广州六一信息科技有限公司fenge广州凡科互联网科技股份有限公司fenge广州凡象科技有限公司fenge广州创想云科技有限公司fenge广州利胜兴信息科技有限公司fenge广州券连通电子商务有限公司fenge广州力得自动化科技有限公司fenge广州功夫投资控股集团有限公司fenge广州化工交易中心有限公司fenge广州医软智能科技有限公司fenge广州十分网络技术有限公司fenge广州千野商务服务有限公司fenge广州千鸟电商科技有限公司fenge广州华工邦元信息技术有限公司fenge广州卓牛信息科技有限公司fenge广州卓绝智能科技有限公司fenge广州卖家宝信息技术咨询有限公司fenge广州南天电脑系统有限公司fenge广州南盾通讯设备有限公司fenge广州博凡网络科技有限公司fenge广州博控自动化技术有限公司fenge广州博日信息科技有限公司fenge广州博通信息技术有限公司fenge广州卡宝宝互联网金融信息服务股份有限公司fenge广州卡盟电子服务有限公司fenge广州即明网络科技有限公司fenge广州友派乐信息科技有限公司fenge广州召隆信息技术有限公司fenge广州合利宝支付科技有限公司fenge广州合富信息科技有限公司fenge广州合摩计算机科技有限公司fenge广州吉仕移动科技股份有限公司fenge广州名科计算机网络有限公司fenge广州君思网络科技有限公司fenge广州和普乐健康科技有限公司fenge广州品途互联网有限公司fenge广州唯控电子科技有限公司fenge广州喜淘信息科技有限公司fenge广州国邦网络科技有限公司fenge广州图匠数据科技有限公司fenge广州圣贸通信息科技有限公司fenge广州埃沃定制科技股份有限公司（IWODE）fenge广州城市规划技术开发服务部fenge广州壹物壹码物联网信息技术有限公司fenge广州壹豆网络科技有限公司fenge广州多融信息科技有限公司fenge广州大为文化股份有限公司fenge广州大白互联网科技有限公司fenge广州天诚伟业通信科技有限公司fenge广州天高软件科技有限公司fenge广州奔步电脑有限公司fenge广州好莱客创意家居股份有限公司fenge广州安创科技有限公司fenge广州安正软件股份有限公司fenge广州宏御生物科技发展有限公司fenge广州宝巨信息技术有限公司fenge广州家愉网络科技有限公司fenge广州宽客科技有限公司fenge广州富米科技有限公司fenge广州富融信息技术有限公司fenge广州尊道电子商务有限公司fenge广州小朋网络科技有限公司fenge广州尚宸企业管理顾问有限公司fenge广州尚恩科技股份有限公司fenge广州展讯信息科技有限公司fenge广州山页信息控制有限公司fenge广州巨辰信息科技有限公司fenge广州市一呼百应网络技术股份有限公司fenge广州市三地信息技术有限公司fenge广州市久泰信息技术有限公司fenge广州市乐商软件科技有限公司fenge广州市云润大数据服务有限公司fenge广州市伟昊科技电子有限公司fenge广州市元善计算机科技有限公司fenge广州市华势信息科技有限公司fenge广州市华奕电子科技有限公司fenge广州市华广计算机软件有限公司fenge广州市华越文化艺术策划有限公司fenge广州市吉特科技有限公司fenge广州市君望机器人自动化有限公司fenge广州市品高软件股份有限公司fenge广州市壹八壹网络科技有限公司fenge广州市天舟通信技术有限公司fenge广州市奔步广告有限公司fenge广州市宇阳数码科技有限公司fenge广州市帝能电子有限公司fenge广州市微嵌计算机科技有限公司fenge广州市恒力检测股份有限公司fenge广州市房企网络科技有限公司fenge广州市拓新化工科技有限公司fenge广州市敏创信息科技有限公司fenge广州市斑马信息科技有限责任公司fenge广州市新干线实业有限公司fenge广州市易杰数码科技有限公司fenge广州市晟卓软件科技有限责任公司fenge广州市景心科技股份有限公司fenge广州市智蓝电子商务有限公司fenge广州市曦风淡淡信息科技有限公司fenge广州市朗恒信息科技有限公司fenge广州市毕酉成信息技术有限公司fenge广州市汇聚支付电子科技有限公司fenge广州市沸腾点信息科技有限公司fenge广州市泰富信通科技有限公司fenge广州市洪邦计算机科技有限公司fenge广州市申迪计算机系统有限公司fenge广州市睿洋网络科技有限公司fenge广州市知微科技有限公司fenge广州市福思特科技有限公司fenge广州市网威信息技术有限公司fenge广州市群书博览教育科技有限公司fenge广州市聚凡信息科技有限公司fenge广州市艾佩克养殖技术咨询有限公司fenge广州市软捷网络科技有限公司fenge广州市迈尔汛科技有限公司fenge广州市金人投资管理有限公司fenge广州市鑫澳康科技有限公司fenge广州市钱大妈农产品有限公司fenge广州市铁山兰实业有限公司fenge广州市领特电子商务有限公司fenge广州市驴迹科技有限责任公司fenge广州市鸿远电子科技有限公司fenge广州市鹤驰信息科技有限公司fenge广州市鼎正信息科技有限公司fenge广州市齐明软件科技有限公司fenge广州布里吉信息科技有限公司fenge广州帝释天软件有限公司fenge广州帝隆科技股份有限公司fenge广州常盈网络股份有限公司fenge广州广日电梯工业有限公司fenge广州广电物业管理有限公司fenge广州广电运通信息科技有限公司fenge广州庆源电子有限公司fenge广州康乐富健康管家有限公司fenge广州微标杆移动互联网科技有限公司fenge广州微革网络科技有限公司fenge广州德峰企业管理有限公司fenge广州德易计算机科技有限公司fenge广州快慢品牌管理有限公司fenge广州快批信息科技有限公司fenge广州快效信息技术有限公司fenge广州思八客科技有限公司fenge广州思普计算机科技有限公司fenge广州思来医疗投资咨询有限公司fenge广州思沛医药科技股份有限公司fenge广州思迈特软件有限公司fenge广州思酷信息科技有限公司fenge广州恒仕珠宝有限公司fenge广州恒利信息科技有限公司fenge广州恒萃信息科技有限公司fenge广州恩志科技有限责任公司fenge广州悠绿游信息技术有限公司fenge广州惠侨计算机科技有限公司fenge广州意品居进出口有限公司fenge广州拓胜计算机技术服务有限公司fenge广州掌时信息科技有限公司fenge广州掌联信息技术有限公司fenge广州擎盾法问大数据科技有限公司fenge广州数夫软件科技有限公司fenge广州斑马体育科技有限公司fenge广州斯沃德科技有限公司fenge广州方联投资咨询有限公司fenge广州无卡数据技术股份有限公司fenge广州明动软件股份有限公司fenge广州易商网信息技术有限公司fenge广州易热捷信息技术有限公司fenge广州易米网络科技有限公司fenge广州星逸文化有限公司fenge广州映博智能科技有限公司fenge广州晟烨信息科技股份有限公司fenge广州智慧城市研究院fenge广州智慧城电子商务有限公司fenge广州智数信息技术有限公司fenge广州智文技术有限公司fenge广州智盈网络科技有限公司fenge广州智网信息技术有限公司fenge广州智能科技发展有限公司fenge广州智野软件科技有限公司fenge广州未山信息科技有限公司fenge广州本安信息科技有限公司fenge广州杰索信息技术有限公司GuangzhouJALsoftInformtaionTechnologyCo.,Ltdfenge广州极飞科技有限公司fenge广州桥汇信息科技有限公司fenge广州橘米全屋品牌策划有限公司fenge广州正虹环境科技有限公司fenge广州比众信息科技有限公司fenge广州比地数据科技有限公司fenge广州汇智通信技术有限公司fenge广州汇通国信科技有限公司fenge广州汉南信息科技有限公司fenge广州汉风科技应用有限公司fenge广州江妙传媒广告有限公司fenge广州河马游戏科技有限公司fenge广州泰达保安服务有限公司越秀分公司fenge广州泰迪智能科技有限公司fenge广州泰�N计算机科技有限公司fenge广州海力特生物科技有限公司fenge广州海晟科技有限公司fenge广州海格星航信息科技有限公司fenge广州润沁教育科技有限公司fenge广州深科信科技信息咨询有限公司fenge广州混沌网络科技有限公司fenge广州潮流服装有限公司fenge广州火数银花信息科技有限公司fenge广州炫成科技有限公司fenge广州爱拍网络科技有限公司fenge广州爱满屋教育咨询有限公司fenge广州爱特安为科技股份有限公司fenge广州玖晔网络科技有限公司fenge广州玖的数码科技有限公司fenge广州环亚化妆品科技有限公司（滋源/美肤宝/法兰琳卡）fenge广州理德物联网科技有限公司fenge广州瑞云网络科技有限公司fenge广州瑞基信息科技有限公司fenge广州申铭信息技术有限公司fenge广州电子口岸管理有限公司fenge广州畅游互动信息技术有限公司fenge广州百信商业有限公司fenge广州盛富和科技有限公司fenge广州码神信息科技有限公司fenge广州碧软信息科技有限公司fenge广州禾信仪器股份有限公司fenge广州禾多云力互联科技有限公司fenge广州秘境科技有限公司fenge广州竞宇金融服务有限公司fenge广州童程童美教育科技有限公司fenge广州米速信息科技有限公司fenge广州粤辰星电子科技有限公司fenge广州纳斯威尔信息技术有限公司fenge广州纳诺科技股份有限公司fenge广州纳财电子商务有限公司fenge广州绝对萌域商贸有限公司fenge广州维尼莱斯服饰有限公司fenge广州缪斯软件科技有限公司fenge广州美人信息技术有限公司fenge广州美好前程信息科技有限公司fenge广州美姿生物科技有限公司fenge广州美盈环境科技有限公司fenge广州翔梦信息技术有限公司fenge广州翰智软件有限公司fenge广州耐奇电气科技有限公司fenge广州联客信息科技有限公司fenge广州腾盈信息技术有限公司fenge广州至拓网络科技有限公司fenge广州致悦信息科技有限公司fenge广州舜辰信息科技有限公司fenge广州艾博智慧软件系统有限公司fenge广州艾曦泰信息科技有限公司fenge广州艾美网络科技有限公司fenge广州蓝道华荣信息科技有限公司fenge广州蜂陶信息技术有限公司fenge广州触众信息科技有限公司fenge广州讯动网络科技有限公司fenge广州诚彩科技有限公司fenge广州诺米品牌管理有限公司fenge广州谷得网络科技有限公司fenge广州豪希睿国际贸易有限公司fenge广州资源投资集团有限公司fenge广州赛宝腾睿信息科技有限公司fenge广州赛意信息科技股份有限公司fenge广州越维信息科技有限公司fenge广州轻创智享科技有限公司fenge广州辉园苑医药科技有限公司fenge广州达人邦信息科技有限公司fenge广州达而球物业管理服务有限公司fenge广州迈傲信息科技有限公司fenge广州迈赫姆电子科技有限公司fenge广州运通购快科技有限公司fenge广州远大信息发展有限公司fenge广州通信研究所（中国电子科技集团公司第七研究所）fenge广州通易科技有限公司fenge广州通达汽车电气股份有限公司fenge广州道然信息科技有限公司fenge广州酷云电子商务有限公司fenge广州酷旅旅行社有限公司fenge广州金乾信息科技有限公司fenge广州铂润信息技术有限公司fenge广州铭峻电子科技有限公司fenge广州银典信息科技有限公司fenge广州银行信用卡中心fenge广州银讯信息科技有限公司fenge广州销路通软件有限公司fenge广州随意门科技有限公司fenge广州雷神安全科技有限公司fenge广州领迅信息科技有限公司fenge广州风寻科技有限公司fenge广州餐道信息科技有限公司fenge广州麟龙信息技术有限公司fenge广州麦根网络科技有限公司fenge广州黑胡子游戏开发有限公司fenge广州鼎甲计算机科技有限公司fenge广州龙骐贸易有限公司fenge广西车便捷环保科技有限公司fenge康美健康管理服务（深圳）有限公司fenge德讯科技股份有限公司fenge恒企教育fenge恒峰信息技术有限公司fenge成都鹏业软件股份有限公司fenge数字广东网络建设有限公司fenge数安时代科技股份有限公司fenge日本KAZUBENTAN汽车制造株式会社广州分公司fenge时互康联健康科技（北京）有限公司（V大夫）fenge普元信息技术股份有限公司fenge普惠医服fenge智捷融汇（大连）科技有限公司fenge杭州中奥科技有限公司fenge林氏木业fenge欧派家居集团股份有限公司fenge欧莱雅（中国）有限公司fenge武汉市润普网络科技有限公司fenge比尔信息技术（北京）有限公司fenge氪金信息科技（天津）有限公司广州分公司fenge江苏润和软件股份有限公司fenge泰斗微电子科技有限公司fenge浙江东方星空数据科技有限公司fenge浙江盛和网络科技有限公司fenge浙江金惠科技有限公司fenge海闻科技有限公司fenge深圳前海新心金融管理有限公司fenge深圳国开创新科技有限公司fenge深圳市中讯合创科技有限公司fenge深圳市乐程软件有限公司fenge深圳市博通智能技术有限公司fenge深圳市名文企业管理咨询有限公司广州分公司fenge深圳市名通科技股份有限公司fenge深圳市商沃科技发展有限公司fenge深圳市小草互联网金融服务有限公司fenge深圳市微视觉科技有限公司广州分公司fenge深圳市德科信息技术有限公司fenge深圳市志行正科技有限公司fenge深圳市拓保软件有限公司fenge深圳市拜特科技股份有限公司fenge深圳市泓健体育文化有限公司fenge深圳市滨海基金管理有限公司fenge深圳市科讯数码有限公司fenge深圳市聚电网络科技有限公司fenge深圳市胜源泉企业管理咨询有限公司fenge深圳市银之杰科技股份有限公司fenge深圳市长亮科技股份有限公司fenge深圳昊汉科技有限公司fenge深圳智慧数联科技有限公司fenge深圳爱思普信息咨询有限公司广州分公司fenge深圳联友科技有限公司fenge深圳脸谱电子商务有限公司fenge深圳达普信科技有限公司fenge清华珠三角研究院fenge湖南金烽信息科技有限公司fenge滴滴优点科技（深圳）有限公司fenge爱云校fenge珠海横琴新区康佰健康家居用品有限公司fenge瑞卡租车fenge用友金融信息技术股份有限公司fenge电讯盈科企业方案fenge畅想互娱（北京）科技有限公司fenge益农控股（广州）有限公司fenge睿哲科技股份有限公司fenge神州信息fenge科力创新软件（广州）有限公司fenge综合平台开发运营中心fenge腾宇融资租赁（广州）有限公司fenge英思达（广州）科技有限公司fenge蓝色海洋互动营销策划（北京）有限公司广州第一分公司fenge讯猫软件（广州）集团有限公司fenge达安基因大众基因产品事业部fenge迪士普研发中心fenge迪昆集团fenge通联支付网络服务股份有限公司广东分公司fenge速达软件技术（广州）有限公司fenge郑州风度软件科技有限公司fenge金税信息技术服务股份有限公司fenge金蝶医疗软件科技有限公司fenge金财互联数据服务有限公司fenge银联数据（CUPD）荣数信息fenge链家信息技术有限公司广州分公司fenge长沙浩微信息科技有限公司fenge雷神互娱fenge青岛汇信科技发展有限公司fenge青木数字技术股份有限公司fenge顺便信息科技有限公司fenge骆驼服饰fenge高诚汇信息科技（广州）有限公司fenge鸿达兴业股份有限公司fenge广东全彩科技有限公司fenge广州万迅电脑软件有限公司fenge广州大为文化股份有限公司";
        return str.split("fenge");
    }




    private String[] getArryZhiWeiStr(){

        String str="项目经理,数据分析师,酒店管理,市场营销,产品运营,室内设计,UI UE设计师";

        return str.split(",");
    }


    private String[] getArryString(){

        String str="广州市天河区广州市天河区天河北路892号8楼808室（地铁3号线华师站B出口）yfxufenge广州天河软件园建中路64-66号佳都商务东203yfxufenge五山路科华街251号乐天创意园A1栋6001yfxufenge番禺区番禺大道北537号番山创业中心1号楼2区604室yfxufenge万科智慧商业广场自编B1栋7层719号房yfxufenge棠德南路28号盈信大厦501yfxufenge天汇LOFT创意园D座首层yfxufenge广州市花都区九塘路8号yfxufenge地铁9号线花都汽车城yfxufenge广州市海珠区阅江路广州国际媒体港西座15楼yfxufenge广州市天河区高普路1029号C栋6楼yfxufenge鹤龙街鹤龙路8号海峡两岸（汇龙）信息产业科技园B区第一层B118号yfxufenge广州市天河区龙口东横街28号丽柏酒店东塔2413-2416室yfxufenge嘉惠苑商业写字楼266室yfxufenge广东省广州市黄浦区开发东区yfxufenge广州天河区珠光新城御景商务大厦四栋二楼yfxufenge明珠工业园丽峰路1号yfxufenge广州市海珠区新港东路万胜广场A塔4楼yfxufenge广州市荔湾区广州圆路1号广州圆大厦yfxufenge合景国际金融广场IFP36楼yfxufenge广州市天河区珠江新城广州周大福金融中心（东塔）13楼yfxufenge南村万博四路42号海大大厦2座9楼yfxufenge广州天河区天河路240号丰兴广场B栋15楼1513室yfxufenge越秀区中山二路18号电信广场yfxufenge华穗路406号之二（保利克洛维A4-2）2613-2620yfxufenge白云区嘉禾望岗地铁B出口 金塬大厦 5Ayfxufenge体育西路111号建和中心15楼1502yfxufenge广州市海珠区新港东路1068号中洲中心北塔1510yfxufenge天河区天河路240号丰兴广场B座15楼1513yfxufenge广州市天河区天河路490号壬丰大厦东厅36楼05室yfxufenge广州天河区天河路240号丰兴广场B栋15楼1513室yfxufenge广州市天河区天河路230号万菱汇yfxufenge广州市白云区西槎路聚龙工业区聚龙街41号（公安宿舍对面）yfxufenge白云大道北756号安华汇营销中心yfxufenge广东省广州市白云区新市连元大厦811yfxufenge广州市天河区天河东路155号骏源大厦24楼晓教育yfxufenge广东省广州市白云区广花三路366号 (邮编：510450)yfxufenge广州市黄埔区科学大道50号绿地中央广场A3栋1705-1709单元 (邮编：510663)yfxufenge越秀金融大厦yfxufenge广州市越秀区东风中路389号壬丰商务大厦yfxufenge天银商贸大厦2110yfxufenge广州市白云区嘉禾嘉禾望岗鹤龙路yfxufenge广州市芳村葵蓬路91号中联茶文化创意园东区3楼 B3-1yfxufenge广州市天河区黄埔大道199号广州阳光酒店yfxufenge番禺大道北354号yfxufenge绿地中央广场A3-2309yfxufenge广州市天河区天河路621号yfxufenge维也纳招聘第二系统yfxufenge广州市越秀区环市东路376号广州易尚国泰大酒店yfxufenge广州市天河区珠江新城花城大道6号yfxufenge珠江新城地铁站A2出口150即可yfxufenge黄埔大道中322号yfxufenge广州天河区建中路66号佳都商务大厦西塔601yfxufenge广州番禺区节能科技园总部大厦2号楼19层yfxufenge广州市越秀区八旗二马路48号广东航运大厦1009室yfxufenge广州黄浦区高新技术开发区莲花砚路8号一楼yfxufenge广州市天河区科韵路16号广州信息港C1栋4楼越秀区天河路45号粤能大厦1501室yfxufenge广州市番禺区番禺大道北555号节能科技园科技发展大厦西座919室yfxufenge广州市白云区京溪桥东侧广州新百佳小商品城A1栋三层自编号A13068yfxufenge广州市天河区中山到道西305号东岳财富广场C座3楼yfxufenge广州市南沙区香江国际金融中心12层yfxufenge广州市天河区燕岭路433号银龙大厦4020yfxufenge科韵路12号方圆e时光大厦东座1101、1104室yfxufenge广东省广州市天河区马场路16号富力盈盛广场B座yfxufenge广州市天河区翰景路1号金星大厦14楼（五山路金山大厦旁边yfxufenge华南师范大学附近）yfxufenge广州市天河区棠下荷光路江韵大厦208yfxufenge厦滘地铁站岭南电商产业园二街三楼314B-315Byfxufenge广州市南沙区东涌镇太石工业区标准工业园2栋yfxufenge黄埔东路3529,3531号鸿森商务中心三楼自编313室yfxufenge新港东路148号邦华环球贸易中心29层 01、02 单元yfxufenge广州市天河区科学城创意大厦yfxufenge广州天河区智汇Park创意园自编11栋复式C2单元yfxufenge广州天河区尚东美御(东门)猎德大道46号（广发银行旁边）yfxufenge广州市 海珠区 磨碟沙(地铁站) 宝地广场5楼505yfxufenge广州天河区锦达信商务大厦A座305yfxufenge广州市 天河区 力达广场A1栋 21楼yfxufenge广州市 天河区 富力盈力大厦北塔 1402yfxufenge广州天河区富力盈隆广场1716室yfxufenge广州市 天河区 天盈广场 东塔11楼yfxufenge广州天河区黄埔大道中336号御发商务中心2楼yfxufenge广州市 天河区 天河区 黄埔大道西路120号高志大厦yfxufenge广州天河区中山大道西路89号天河软件园华景园区B栋西梯五楼整层yfxufenge广州海珠区新港东路1088号中州交易中心1610yfxufenge广州天河区保利·中达广场2号楼1306室yfxufenge广州市 天河区 银汇大厦 天河区龙怡路117号银汇大厦1005房yfxufenge广州天河区丽柏国际酒店2703yfxufenge广州天河区高科大厦B座13A楼03室yfxufenge广州市 越秀区 淘金家园 广州市越秀区淘金东路62号淘金家园83号yfxufenge广州市 番禺区 冠军大厦 六层yfxufenge广州天河区羊城国际商贸中心西塔yfxufenge广州天河区创境汇盈科智谷3栋115";

        return str.split("yfxufenge");
    }

    @Test
    public void testArrStr(){
        String arrStr[]=getArryString();
        System.out.println(arrStr.length);
    }

    @Test
    public void testConn(){
        SqlSession sqlSession=getSqlSession();
        PadataTwoMapper padataTwoMapper=sqlSession.getMapper(PadataTwoMapper.class);

        PadataTwo padataTwo=padataTwoMapper.selectPadataTwoById(6000);

        System.out.println(padataTwo);

        if (padataTwo==null){
            System.out.println("----------------------");
            System.out.println("null");
        }

        sqlSession.close();
    }
}
